alertmanager_version: "0.28.1"

alertmanager_user: alertmanager
alertmanager_group: alertmanager

alertmanager_install_dir: /opt/alertmanager
alertmanager_config_dir: /etc/alertmanager
alertmanager_data_dir: /var/lib/alertmanager

alertmanager_config_file: /etc/alertmanager/alertmanager.yml
alertmanager_candidate_config_file: /tmp/alertmanager-config-candidate.yml
alertmanager_service_name: alertmanager

alertmanager_port: 9093

alertmanager_arch: "{{ {'x86_64': 'amd64', 'aarch64': 'arm64'}[ansible_facts['architecture']] }}"

alertmanager_download_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ alertmanager_arch }}.tar.gz"
alertmanager_archive_filename: "alertmanager-{{ alertmanager_version }}.linux-{{ alertmanager_arch }}.tar.gz"
alertmanager_archive_path: "{{ alertmanager_download_dir }}/{{ alertmanager_archive_filename }}"

alertmanager_download_dir: /tmp

alertmanager_checksum_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/sha256sums.txt"
alertmanager_checksum_file: "{{ alertmanager_download_dir }}/alertmanager-sha256sums.txt"
alertmanager_discord_send_resolved: true
