grafana_package_name: grafana
grafana_service_name: grafana-server

grafana_config_dir: /etc/grafana
grafana_config_file: /etc/grafana/grafana.ini

grafana_port: 3000

grafana_apt_key_url: https://apt.grafana.com/gpg-full.key
grafana_apt_keyring: /etc/apt/keyrings/grafana.asc

grafana_provisioning_dir: /etc/grafana/provisioning

grafana_datasources_dir: /etc/grafana/provisioning/datasources

grafana_datasources_file: /etc/grafana/provisioning/datasources/datasources.yml

grafana_prometheus_url: http://localhost:9090

grafana_loki_url: http://localhost:3100
