all:
  vars:
    ansible_user: root
  children:
    observability:
      hosts:
        ubuntu:
          ansible_host: 192.168.0.30

    monitored:
      hosts:
        centos:
          ansible_host: 192.168.0.20
        rocky:
          ansible_host: 192.168.0.10
