loki_version: "3.7.8"
loki_arch: "{{ {'x86_64': 'amd64', 'aarch64': 'arm64'}[ansible_facts['architecture']] }}"
loki_user: loki
loki_group: loki

loki_install_dir: /opt/loki
loki_release_dir: "{{ loki_install_dir }}/releases/{{ loki_version }}"
loki_archive_path: "/tmp/loki-{{ loki_version }}-{{ loki_arch }}.zip"
loki_release_binary: "{{ loki_release_dir }}/loki-linux-{{ loki_arch }}"
loki_binary_path: "{{ loki_install_dir }}/loki"

loki_config_dir: /etc/loki
loki_data_dir: /var/lib/loki

loki_config_file: /etc/loki/loki-config.yml
loki_service_name: loki
loki_candidate_config_file: /tmp/loki-config-candidate.yml

loki_port: 3100

loki_download_url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-{{ loki_arch }}.zip"
